EComm2022.Web/Controllers/CiudadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using EComm2022.Entidades.Entidades;
using EComm2022.Servicios.Servicios.Facades;
using Newtonsoft.Json;

namespace EComm2022.Web.Controllers
{
    public class CiudadController : Controller
    {
        private IServicioCiudades servicio;

        public CiudadController(IServicioCiudades servicio)
        {
            this.servicio = servicio;
        }
        // GET: Ciudad
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarCiudadesPorPais(int id)
        {
            var lista = servicio.GetListaPorPais(id);
            return Json(lista, JsonRequestBehavior.AllowGet);
        }




        [HttpGet]
        public JsonResult ListarCiudades()
        {
            var lista = servicio.GetLista();
            return Json(new {data=lista}, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult GuardarCiudad(string objeto)
        {
            object resultado = null;
            string mensaje = string.Empty;
            try
            {
                Ciudad ciudadRecibida = new Ciudad();
                ciudadRecibida = JsonConvert.DeserializeObject<Ciudad>(objeto);

                mensaje = ValidarCiudad(ciudadRecibida);
                if (mensaje == String.Empty)
                {
                    if (!servicio.Existe(ciudadRecibida))
                    {
                        servicio.Guardar(ciudadRecibida);
                        resultado = ciudadRecibida.CiudadId;
                        mensaje = "Ciudad agregada/editada";
                    }
                    else
                    {
                        resultado = 0;
                        mensaje = "Ciudad existente!!!";
                    }
                }
                else
                {
                    resultado = 0;
                }
            }
            catch (Exception e)
            {
                resultado = 0;
                mensaje = e.Message;

            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        private string ValidarCiudad(Ciudad ciudad)
        {
            StringBuilder sb = new StringBuilder();
            if (string.IsNullOrEmpty(ciudad.NombreCiudad))
            {
                sb.AppendLine("Nombre de la ciudad requerido");
            }

            if (ciudad.ProvinciaId == 0)
            {
                sb.AppendLine("Debe seleccionar una provincia");
            }
            return sb.ToString();
        }

        [HttpPost]
        public JsonResult EliminarCiudad(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            try
            {
                Ciudad c = servicio.GetCiudadPorId(id);
                if (!servicio.EstaRelacionada(c))
                {
                    servicio.Borrar(c);
                    respuesta = true;
                    mensaje = "Registro eliminado";
                }
                else
                {
                    respuesta = false;
                    mensaje = "Registro relacionado... Baja denegada";
                }
            }
            catch (Exception e)
            {
                respuesta = false;
                mensaje = e.Message;
            }

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

    }
}

EComm2022.Web/Controllers/ProvinciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using EComm2022.Entidades.Entidades;
using EComm2022.Servicios.Servicios.Facades;

namespace EComm2022.Web.Controllers
{
    public class ProvinciaController : Controller
    {
        private readonly IServicioProvincias servicio;
        // GET: Provincia
        public ProvinciaController(IServicioProvincias servicio)
        {
            this.servicio = servicio;
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarProvincias()
        {
            var lista = servicio.GetLista();
            return Json(new{data=lista}, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarProvincia(Provincia provinciaRecibida)
        {
            object resultado = null;
            string mensaje = string.Empty;
            try
            {
                mensaje = ValidarProvincia(provinciaRecibida);
                if (mensaje==String.Empty)
                {
                    if (!servicio.Existe(provinciaRecibida))
                    {
                        servicio.Guardar(provinciaRecibida);
                        resultado = provinciaRecibida.ProvinciaId;
                        mensaje = "Provincia agregada/editada";
                    }
                    else
                    {
                        resultado = 0;
                        mensaje = "Provincia existente!!!";
                    }
                }
                else
                {
                    resultado = 0;
                }
            }
            catch (Exception e)
            {
                resultado = 0;
                mensaje = e.Message;

            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        private string ValidarProvincia(Provincia provincia)
        {
            StringBuilder sb = new StringBuilder();
            if (string.IsNullOrEmpty(provincia.NombreProvincia))
            {
                sb.AppendLine("Nombre de la provincia requerido");
            }

            return sb.ToString();
        }
        [HttpPost]
        public JsonResult EliminarProvincia(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            try
            {
                Provincia p = servicio.GetProvinciaPorId(id);
                if (!servicio.EstaRelacionado(p))
                {
                    servicio.Borrar(p);
                    respuesta = true;
                    mensaje = "Registro eliminado";
                }
                else
                {
                    respuesta = false;
                    mensaje = "Registro relacionado... Baja denegada";
                }
            }
            catch (Exception e)
            {
                respuesta = false;
                mensaje = e.Message;
            }

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

    }
}

EComm2022.Web/Views/Ciudad/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<ol class="breadcrumb mt-4 mb-4 ">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Dashboard</a></li>
    <li class="breadcrumb-item active">Ciudades</li>
</ol>
<div class="card">
    <h5 class="card-header bg-primary text-white">
        <i class="fas fa-bookmark"></i>
        Listado de Ciudades

    </h5>
    <div class="card-body">
        <button type="button" class="btn btn-primary" onclick="abrirModal()"><i class="fas fa-plus"></i></button>
        <hr />
        <table id="tabla" class="table display cell-border" style="width: 100%">
            <thead>
                <tr>
                    <th>Ciudad</th>
                    <th>Provincia</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Ciudades</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="txtCiudadId" value="0" />
                <div class="row">
                    <div class="col-md-12">
                        <label for="txtNombreCiudad" class="form-label">Nombre Ciudad</label>
                        <input type="text" class="form-control" id="txtNombreCiudad" placeholder="Ingrese nombre">
                    </div>
                
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label for="cboProvincia" class="form-label">Provincia</label>

                        <select id="cboProvincia" class="form-select" aria-label="Default select example">
                        </select>
                    </div>


                    <div class="col-md-6">
                        <label for="cboActivo" class="form-label">Activo</label>

                        <select id="cboActivo" class="form-select" aria-label="Default select example">
                            <option value="1">SI</option>
                            <option value="0">NO</option>
                        </select>
                    </div>
                </div>
                
                <div class="row mt-3">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script>


        var tablaCiudades;
        var filaSeleccionada;


        $(document).ready(function() {
            cargarTabla();
            cargarCboProvincias();

            $("#tabla tbody").on("click",
                '.btn-editar',
                function() {
                    filaSeleccionada = $(this).closest("tr");
                    var datos = tablaCiudades.row(filaSeleccionada).data();
                    abrirModal(datos);

                });

            $("#tabla tbody").on("click",
                ".btn-borrar",
                function() {
                    var ciudadSeleccionada = $(this).closest("tr");
                    var datosCiudad = tablaCiudades.row(ciudadSeleccionada).data();

                    console.log(datosCiudad);
                    debugger;
                    swal({
                            title: "¿Está seguro?",
                            text: "¿Desea eliminar el registro seleccionado?",
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonClass: "btn-danger",
                            confirmButtonText: "SI",
                            cancelButtonText:"NO",
                            closeOnConfirm: false
                        },
                        function () {

                            jQuery.ajax({
                                url: "@Url.Action("EliminarCiudad","Ciudad")",
                                type: "POST",
                                data: JSON.stringify({ id: datosCiudad.CiudadId}),
                                dataType: "json",
                                contentType: "application/json; charset=utf-8",
                                success: function (data) {

                                    if (data.resultado) {
                                        tablaCiudades.row(ciudadSeleccionada).remove().draw();
                                        swal("Borrado!", "Registro eliminado!!!", "success");
                                    } else {
                                        swal("No se pudo eliminar!", data.mensaje, "error");
                                    }


                                },
                                error:function(error) {
                                    console.log(error);
                                },
                                beforeSend:function() {

                                }
                            });


                        });
                });


        });


        function cargarCboProvincias() {
            jQuery.ajax({
                url: "@Url.Action("ListarProvincias", "Provincia")",
                type: "GET",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (provincias) {
                    console.log(provincias);
                    debugger;
                    $("#cboProvincia").append('<option disabled value="0">'
                        +"Seleccione" + '</option>');
                    $.each(provincias.data,
                        function (index, provincia) {
                            $("#cboProvincia").append('<option value="'
                                + provincia.ProvinciaId + '">'
                                + provincia.NombreProvincia + '</option>');
                        });

                }
            });


        }


        function abrirModal(jsonCiudad) {

            $("#mensajeError").hide();
            $("#txtCiudadId").val(0);
            $("#txtNombreCiudad").val("");
            $("#cboActivo").val(1);
            $("#cboProvincia").val($("#cboProvincia option:first").val());
            if (jsonCiudad != null) {
                $("#txtCiudadId").val(jsonCiudad.CiudadId);
                $("#txtNombreCiudad").val(jsonCiudad.NombreCiudad);
                $("#cboActivo").val(jsonCiudad.Activo == true ? 1 : 0);
                $("#cboProvincia").val(jsonCiudad.ProvinciaId);

            }
            $("#FormModal").modal("show");
        }


        function cargarTabla() {
            tablaCiudades = $("#tabla").DataTable({
                responsive: "true",
                ordering: "false",
                "ajax": {
                    url: "@Url.Action("ListarCiudades", "Ciudad")",
                    type: "GET",
                    dataType: "json"
                },
                "columns": [
                    { "data": "NombreCiudad" },
                    {
                        "data": "Provincia",
                        render: function(data) {
                            return data.NombreProvincia;
                        }
                    },
                    {
                        "data": "Activo",
                        render: function(valorDeActivo) {
                            if (valorDeActivo) {
                                return '<span class="badge text-bg-success">SI</span>';
                            } else {
                                return '<span class="badge text-bg-danger">NO</span>';

                            }
                        }
                    },
                    {
                        "defaultContent": '<button type="button" class="btn btn-warning mx-3 btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                            '<button type="button" class="btn btn-danger btn-sm btn-borrar"><i class="fas fa-trash"></i></button>',
                        "orderable": false,
                        "searchable": false,
                        "width": "90px"

                    }
                ]

            });
        }

        function Guardar() {
            var ciudad = {
                CiudadId: $("#txtCiudadId").val(),
                NombreCiudad: $("#txtNombreCiudad").val(),
                Activo: $("#cboActivo").val() == 1 ? true : false,
                ProvinciaId: $("#cboProvincia option:selected").val(),
                Provincia: {
                    ProvinciaId: $("#cboProvincia option:selected").val(),
                    NombreProvincia: $("#cboProvincia option:selected").text()
                }
            };
            console.log(ciudad);
            debugger;
            var request = new FormData();
            request.append("objeto", JSON.stringify(ciudad));

            jQuery.ajax({
                url: "@Url.Action("GuardarCiudad", "Ciudad")",
                type: "POST",
                data: request,
                processData: false,
                contentType: false,
                success: function(data) {
                    $(".modal-body").LoadingOverlay("hide");

                    if (ciudad.CiudadId == 0) {
                        debugger;
                        if (data.resultado != 0) {
                            ciudad.CiudadId = data.resultado;
                            tablaCiudades.row.add(ciudad).draw(false);
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    } else {
                        if (data.resultado != 0) {
                            tablaCiudades.row(filaSeleccionada).data(ciudad).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal('hide');

                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }


                    }

                },
                error: function(error) {

                },
                beforeSend: function() {
                    $(".modal-body").LoadingOverlay("show",
                        {
                            imageResizeFactory: 2,
                            text: "Guardando...",
                            size: 14
                        });

                }
            });
        }

    </script>
}