EComm2022.Web/Controllers/ProveedorController.cs
using System;
using System.Text;
using System.Web.Mvc;
using EComm2022.Entidades.Entidades;
using EComm2022.Servicios.Servicios.Facades;
using Newtonsoft.Json;

namespace EComm2022.Web.Controllers
{
    public class ProveedorController : Controller
    {
        private IServicioProveedores servicio;

        public ProveedorController(IServicioProveedores servicio)
        {
            this.servicio = servicio;
        }
        // GET: Proveedor
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarProveedores()
        {
            var lista = servicio.GetLista();
            return Json(new {data=lista}, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult GuardarProveedor(string objeto)
        {
            object resultado = null;
            string mensaje = string.Empty;
            try
            {
                Proveedor proveedorRecibido = new Proveedor();
                proveedorRecibido = JsonConvert.DeserializeObject<Proveedor>(objeto);

                mensaje = ValidarProveedor(proveedorRecibido);
                if (mensaje == String.Empty)
                {
                    if (!servicio.Existe(proveedorRecibido))
                    {
                        servicio.Guardar(proveedorRecibido);
                        resultado = proveedorRecibido.CiudadId;
                        mensaje = "Proveedor agregada/editada";
                    }
                    else
                    {
                        resultado = 0;
                        mensaje = "Proveedor existente!!!";
                    }
                }
                else
                {
                    resultado = 0;
                }
            }
            catch (Exception e)
            {
                resultado = 0;
                mensaje = e.Message;

            }

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        private string ValidarProveedor(Proveedor proveedor)
        {
            StringBuilder sb = new StringBuilder();
            if (string.IsNullOrEmpty(proveedor.NombreProveedor))
            {
                sb.AppendLine("Nombre del proveedor requerido" + Environment.NewLine);
            }
            if (string.IsNullOrEmpty(proveedor.Direccion))
            {
                sb.AppendLine("Dirección requerida" + Environment.NewLine);
            }


            if (proveedor.ProvinciaId == 0)
            {
                sb.AppendLine("Debe seleccionar una provincia" + Environment.NewLine);
            }
            if (proveedor.CiudadId == 0)
            {
                sb.AppendLine("Debe seleccionar una ciudad" + Environment.NewLine);
            }
            if (string.IsNullOrEmpty(proveedor.Telefono))
            {
                sb.AppendLine("Teléfono requerido" + Environment.NewLine);
            }

            return sb.ToString();

        }

    }
}

EComm2022.Web/Views/Proveedor/Index.cshtml
<ol class="breadcrumb mt-4 mb-4 ">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Dashboard</a></li>
    <li class="breadcrumb-item active">Proveedores</li>
</ol>
<div class="card">
    <h5 class="card-header bg-primary text-white">
        <i class="fas fa-bookmark"></i>
        Listado de Proveedores

    </h5>
    <div class="card-body">
        <button type="button" class="btn btn-primary" onclick="abrirModal()"><i class="fas fa-plus"></i></button>
        <hr />
        <table id="tabla" class="table display cell-border" style="width: 100%">
            <thead>
                <tr>
                    <th>Proveedor</th>
                    <th>Direccion</th>
                    <th>Ciudad</th>
                    <th>Provincia</th>
                    <th>Telefono</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Proveedor</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="txtProveedorId" value="0" />
                <div class="row">
                    <div class="col-md-12">
                        <label for="txtNombreProveedor" class="form-label">Nombre Proveedor</label>
                        <input type="text" class="form-control" id="txtNombreProveedor" placeholder="Ingrese nombre">
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="txtDireccion" class="form-label">Dirección</label>
                        <input type="text" class="form-control" id="txtDireccion" placeholder="Ingrese dirección">

                    </div>

                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label for="cboProvincia" class="form-label">Provincia</label>
                        <select id="cboProvincia" class="form-select" aria-label="Default select example" onchange="cargarCiudades()">
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label for="cboCiudad" class="form-label">Ciudad</label>
                        <select id="cboCiudad" class="form-select" aria-label="Default select example">
                        </select>
                    </div>


                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label for="txtTelefono" class="form-label">Teléfono</label>
                        <input type="text" class="form-control" id="txtTelefono" placeholder="Ingrese TE">
                    </div>

                    <div class="col-md-6">
                        <label for="cboActivo" class="form-label">Activo</label>

                        <select id="cboActivo" class="form-select" aria-label="Default select example">
                            <option value="1">SI</option>
                            <option value="0">NO</option>
                        </select>
                    </div>

                </div>
                <div class="row mt-3">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script>

        var tablaProveedores;
        var filaSeleccionada;

        $(document).ready(function() {
            cargarTabla();
            cargarCboProvincias();

            $("#tabla tbody").on("click",
                '.btn-editar',
                function() {
                    filaSeleccionada = $(this).closest("tr");
                    var datos = tablaProveedores.row(filaSeleccionada).data();
                    abrirModal(datos);

                });

        });

        function cargarTabla() {
                tablaProveedores = $("#tabla").DataTable({
                responsive: "true",
                ordering: "false",
                "ajax": {
                    url: "@Url.Action("ListarProveedores", "Proveedor")",
                    type: "GET",
                    dataType: "json"
                },
                "columns": [
                    { "data": "NombreProveedor" },
                    { "data": "Direccion" },
                    {
                        "data": "Ciudad",
                        render: function (data) {
                        return data.NombreCiudad;
                        }
                    },
                    {
                        "data": "Provincia",
                        render: function(data) {
                            return data.NombreProvincia;
                        }
                    },
                    {"data":"Telefono"},
                    {
                        "data": "Activo",
                        render: function(valorDeActivo) {
                            if (valorDeActivo) {
                                return '<span class="badge text-bg-success">SI</span>';
                            } else {
                                return '<span class="badge text-bg-danger">NO</span>';

                            }
                        }
                    },
                    {
                        "defaultContent": '<button type="button" class="btn btn-warning mx-3 btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                            '<button type="button" class="btn btn-danger btn-sm btn-borrar" ><i class="fas fa-trash"></i></button>',
                        "orderable": false,
                        "searchable": false,
                        "width": "90px"

                    }
                ],
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json"
                }


            });
        }


        function cargarCboProvincias() {
             jQuery.ajax({
                url: "@Url.Action("ListarProvincias", "Provincia")",
                type: "GET",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (provincias) {
                    console.log(provincias);
                    //debugger;
                    $("#cboProvincia").append('<option disabled value="0">'
                        +"Seleccione" + '</option>');
                    $.each(provincias.data,
                        function (index, provincia) {
                            $("#cboProvincia").append('<option value="'
                                + provincia.ProvinciaId + '">'
                                + provincia.NombreProvincia + '</option>');
                        });

                }
             });


        }

        function cargarCiudades() {
            $("#cboCiudad").empty();
            $("#cboCiudad").append('<option value="0" disabled>Seleccionar</option>');

            $.ajax({
                url: '@Url.Action("ListarCiudadesPorPais","Ciudad")',
                type: 'GET',
                dataType: 'json',
                data: {
                    id: $("#cboProvincia").val()

                },
                success: function (ciudades) {
                    console.log(ciudades);
                    //debugger;
                    $.each(ciudades,
                        function(i, ciudad) {
                            $("#cboCiudad").append('<option value="' + ciudad.CiudadId + '">' + ciudad.NombreCiudad + '</option>');
                        });
                    $("#cboCiudad").val($("#cboCiudad option:first").val());
                },
                error: function(ex) {
                    alert('Error al intentar cargar las ciudades.' + ex);
                }
            });
            return false;
        };



        function abrirModal(jsonProveedor) {

            $("#mensajeError").hide();
            $("#txtProveedorId").val(0);
            $("#txtNombreProveedor").val("");
            $("#txtDireccion").val("");
           $("#txtTelefono").val("");
            $("#cboActivo").val(1);
            $("#cboProvincia").val($("#cboProvincia option:first").val());
            $("#cbociudad").empty();
            if (jsonProveedor != null) {
                cargarCboCiudades(jsonProveedor.ProvinciaId);
                $("#txtProveedorId").val(jsonProveedor.ProveedorId);
                $("#txtNombreProveedor").val(jsonProveedor.NombreProveedor);
                $("#txtDireccion").valueOf(jsonProveedor.Direccion);
                $("#cboActivo").val(jsonProveedor.Activo == true ? 1 : 0);
                $("#cboProvincia").val(jsonProveedor.ProvinciaId);
                $("#cboCiudad").val(jsonProveedor.CiudadId);
                $("#txtTelefono").val(jsonProveedor.Telefono);

            }
            $("#FormModal").modal("show");
        }



        function Guardar() {
            var proveedor = {
                ProveedorId:$("#txtProveedorId").val(),
                NombreProveedor: $("#txtNombreProveedor").val(),
                Direccion:$("#txtDireccion").val(),
                Activo: $("#cboActivo").val() == 1 ? true : false,
                ProvinciaId: $("#cboProvincia option:selected").val(),
                Provincia: {
                    ProvinciaId: $("#cboProvincia option:selected").val(),
                    NombreProvincia: $("#cboProvincia option:selected").text()
                },
                CiudadId: $("#cboCiudad option:selected").val(),
                Ciudad: {
                    CiudadId: $("#cboCiudad option:selected").val(),
                    NombreCiudad: $("#cboCiudad option:selected").text()
                },
                Telefono:$("#txtTelefono").val()
            };
            console.log(proveedor);
            //debugger;
            var request = new FormData();
            request.append("objeto", JSON.stringify(proveedor));

            jQuery.ajax({
                url: "@Url.Action("GuardarProveedor", "Proveedor")",
                type: "POST",
                data: request,
                processData: false,
                contentType: false,
                success: function (data) {
                    $(".modal-body").LoadingOverlay("hide");

                    if (proveedor.ProveedorId == 0) {
                        debugger;
                        if (data.resultado != 0) {
                            proveedor.ProveedorId = data.resultado;
                            tablaProveedores.row.add(proveedor).draw(false);
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }

                    } else {
                        if (data.resultado != 0) {
                            tablaProveedores.row(filaSeleccionada).data(proveedor).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal('hide');

                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }


                    }

                },
                error: function(error) {

                },
                beforeSend: function() {
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactory: 2,
                        text: "Guardando...",
                        size: 14
                    });

                }
            });


        }


    </script>
}